# Site
repository: sproogen/resume-theme
favicon:

# Content configuration version
version: 2

# Personal info
name: 최운식
title: JAVA Back-end Developer
email: woonsik.dev@gmail.com
web: https://ws-pace.tistory.com/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: choiwoonsik
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
#   - title: itsgoingto.be
#     icon: fas fa-globe
#     url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile
about_content: |
  안녕하세요. 자바 백엔드 개발자 최운식입니다.

  주요 스킬 : <mark>JAVA</mark> and <mark>Spring Boot</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title: 
            icon: 
            url: 
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          
        description: | # this will include new lines to allow paragraphs

    content:
      - layout: left
        title:
        link:
        # link_text: Project Website
        additional_links:
          - title: 
            icon: 
            url: 
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          
        description: | # this will include new lines to allow paragraphs

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 상명대학교
        caption: 2016. 03 - 2023. 02 (현재 4학년 1학기 재학중)
        sub_title: SW융합학부 컴퓨터과학전공
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          졸업 프로젝트 진행 중
            - 배터리 셀 ~

          총 학점 : 3.38 / 4.5
          전공 : 3.58 / 4.5


  - title: 외부활동
    layout: text
    content: | # this will include new lines to allow paragraphs
      기술 블로그를 운영중에 있습니다.
      - [REST API 스프링 부트 프로젝트](https://ws-pace.tistory.com/category/Web/%EC%8A%A4%ED%94%84%EB%A7%81%EB%B6%80%ED%8A%B8%20RestAPI%20%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8)
      - [토스페이먼츠 PG 연동 시리즈](https://ws-pace.tistory.com/category/%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8/%ED%86%A0%EC%8A%A4%ED%8E%98%EC%9D%B4%EB%A8%BC%EC%B8%A0%20%EA%B2%B0%EC%A0%9C%20%EC%8B%9C%EC%8A%A4%ED%85%9C%20%EC%A0%81%EC%9A%A9%20%EC%8B%9C%EB%A6%AC%EC%A6%88)
      - [CS - 전공 수업 정리](https://ws-pace.tistory.com/category/CS)

# Footer
footer_show_references: true
references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
