# Site
repository: choiwoonsik/choiwoonsik.github.io
favicon:

# Content configuration version
version: 2

# Personal info
name: 최운식
title: JAVA Back-end Developer
email: woonsik.dev@gmail.com
website: https://ws-pace.tistory.com/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: choiwoonsik
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
#   - title: itsgoingto.be
#     icon: fas fa-globe
#     url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  안녕하세요. 자바 백엔드 개발자 최운식입니다.

# Projects Section
# projects_title: Projects

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 코디네이터 1:1 매칭 패션 플랫폼 - 스타일멘토
        link: https://github.com/Sigma-i-2022/backend/tree/develop
        caption: 2021. 12 ~ 현재
        # link_text: Project Website
        additional_links:
          - title: GooglePlay
            icon:
            url: https://play.google.com/store/apps/details?id=com.sigmai.stylemento
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          예비창업패키지, 학생 창업유망팀 300 선발을 목표로 현재 진행중에 있습니다.

        description: | # this will include new lines to allow paragraphs
          - (토스페이먼츠 PG 시스템)[https://ws-pace.tistory.com/category/%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8/%ED%86%A0%EC%8A%A4%ED%8E%98%EC%9D%B4%EB%A8%BC%EC%B8%A0%20%EA%B2%B0%EC%A0%9C%20%EC%8B%9C%EC%8A%A4%ED%85%9C%20%EC%A0%81%EC%9A%A9%20%EC%8B%9C%EB%A6%AC%EC%A6%88] 기반 결제 시스템 구현
          - [금융결제원 오픈뱅킹 OpenAPI](https://ws-pace.tistory.com/231?category=1010992)를 이용한 계좌실명조회 기능 구현
          - Junit 5 및 BDD Mockito 를 사용하여 API, DB (JPA), Service 로직 테스트 코드 작성
          - Web Socket을 이용해 사용자와 코디네이터간 실시간 채팅 구현
          - Spring Boot Mail을 이용해 이메일 인증을 통한 회원가입 구현
          - 토스페이먼츠 서브몰 등록 API 개발 때 [공식문서 오류 정정기](https://ws-pace.tistory.com/242?category=1010992)

          언어 : Java
          서버 : AWS EC2, RDS, S3
          데이터베이스 : MySql
          프레임워크 : Spring Boot, Spring Data JPA, Gradle, Swagger
          외부 API : 토스페이먼츠 PG, 금융결제원 오픈뱅킹 오픈API

      - layout: top-middle
        title: 리그오브레전드 스펠/궁극기 체크 도움 웹 서비스 ([스우미](https://swoomi.me))
        link: https://github.com/Team-Swoomi/swoomi-backend
        # link_text: Project Website
        additional_links:
          - title:
            icon:
            url:
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          - Redis를 이용해 캐시메모리 적용하여 쿼리 최적화 및 50% 응답속도 개선
          - nGrinder를 이용해 가상 트래픽을 발생시켜 서버 내구성 테스트, Redis 적용 후 2배 이상의 트래픽 처리 능력 향상 검증
          - HiKariCP를 이용해 DB 커넥션 풀 관리
          - Junit4를 이용해 통합 테스트 진행
          - [Web Socket](https://ws-pace.tistory.com/category/Web/%EC%8A%A4%ED%94%84%EB%A7%81%EB%B6%80%ED%8A%B8%20WebSocket%20%EC%A0%81%EC%9A%A9%EA%B8%B0)을 이용해 실시간 팀원 간 정보 동기화 구현
          - Git web hook + [Jenkins](https://ws-pace.tistory.com/category/Web/Jenkins%20%EC%A0%95%EB%A6%AC%EA%B8%80)를 이용한 CI/CD 구현 및 Slack 연동
          - 도메인 구매 후 TLS를 이용해 HTTPS 적용
          - Spring boot mail을 이용해 예외 발생 시 지정된 이메일로 에러 내용 발송
          - 약 4개월 이상 실제 서비스 운용 중이며 평균 DAU 15 이상 유지 중
          - 제 1회 OPGG 정보통신 경진대회에 참가하여 우승 및 [인터뷰](https://m.post.naver.com/viewer/postView.naver?volumeNo=32651307&memberNo=24985926) - [수료증](https://hackathon.op.gg/users/yZezVI4Zhc)

      - layout: top-middle
        title: 스프링 부트 기반 REST API + OAuth 로그인 웹 애플리케이션 제작
        link: https://github.com/choiwoonsik/springboot_RestApi_App_Project
        additional_links:
        - title: 블로그 정리
          icon:
          url: https://ws-pace.tistory.com/category/Web/%EC%8A%A4%ED%94%84%EB%A7%81%EB%B6%80%ED%8A%B8%20RestAPI%20%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8
          description: |
            - MVC 구조의 웹 백엔드를 구현
            - RestControllerAdvice + ExceptionHandler를 이용한 통합 에러 처리 구현
            - 제네릭스를 이용하여 템플릿 메소드 패턴으로 서버 응답을 가지도록 구현
            - Spring Security + JWT을 이용해 Access Token, Refresh Token을 사용하는 토큰 기반 인증 구현
            - OAuth2.0을 이용하여 카카오 간편 로그인 구현
            - JUnit을 이용하여 MockUser 테스트 등 단위/통합 테스트 진행

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 
        sub_title: 
        link: 
        # link_text: boringcompany.com
        caption: 
        quote: >

        description: | # this will include new lines to allow paragraphs


  # - title: Opensource
  #   layout: list
  #   content:
  #     - layout: top-middle
  #       title: 개인 기술블로그
  #       link: https://ws-pace.tistory.com/
  #       description: |
  #       - 학습 중 맞닥뜨렸던 문제점들에 대한 해결 경험과 학교 및 인터넷 강의, 알고리즘 등 공부한 내용들을 꾸준하게 정리하고 있습니다.

  - title: Skill
    layout: list
    content:
      - layout: top-middle
        title: Backend
        description: |
        - Java
        - Spring Boot, Spring MVC, Spring Security, Spring Data JPA, Redis, Spring Cloud Netflix
        - JPA, Hibernate
        - JUnit4/5, BDD Mockito, nGrinder
        - Gradle, Swagger
        - Linux, IntelliJ, Git/Github

      - layout: top-middle
        title: DevOps
        description: |
        - AWS EC2, RDS, IAM, Cloud Watch, S3
        - Jenkins
        - MySql, H2

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 상명대학교
        sub_title: SW융합학부 컴퓨터과학전공
        link: https://ws-pace.tistory.com/category/CS
        caption: |
          2016. 03 - 2023. 02 
          (현재 4학년 1학기 재학중)
        quote: >

        description: | # this will include new lines to allow paragraphs
        - 운영체제, 네트워크, 리눅스 프로그래밍 수업 등을 들으며 컴퓨터 내외 전반적인 프로토콜에 대한 지식 함양
        - 알고리즘, 자료구조 수업을 통해 다양한 자료구조 및 알고리즘에 대한 접근 방법과 풀이 방법 학습
        - 객체지향 프로그래밍 수업을 통해 다양한 디자인 패턴의 구조 및 활용 방법 학습
    
       - layout: top-middle
        title: 42 서울
        caption: 2020. 05. 25 ~ 2020. 07.25
        link: https://github.com/choiwoonsik/my42-Seoul
        description: |
        - Linux manual과 C언어 책을 참고해 구현 목적과 입력, 반환 값 등 내부 구조를 바탕으로 printf() 등 C 라이브러리 함수 구현 과제 수행

  - title: 외부활동
    layout: text
    content: | # this will include new lines to allow paragraphs
      기술 블로그를 운영중에 있습니다.
      - [REST API 스프링 부트 프로젝트](https://ws-pace.tistory.com/category/Web/%EC%8A%A4%ED%94%84%EB%A7%81%EB%B6%80%ED%8A%B8%20RestAPI%20%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8)
      - [토스페이먼츠 PG 연동 시리즈](https://ws-pace.tistory.com/category/%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8/%ED%86%A0%EC%8A%A4%ED%8E%98%EC%9D%B4%EB%A8%BC%EC%B8%A0%20%EA%B2%B0%EC%A0%9C%20%EC%8B%9C%EC%8A%A4%ED%85%9C%20%EC%A0%81%EC%9A%A9%20%EC%8B%9C%EB%A6%AC%EC%A6%88)
      - [CS - 전공 수업 정리](https://ws-pace.tistory.com/category/CS)

# Footer
footer_show_references: true
references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
